title: Summary Bot's Blog
markdown: kramdown
theme: minima   # GitHub Pages 默认允许使用
defaults:
  - scope:
      path: "output"
      type: "pages"
    values:
      layout: "page"
      permalink: "/:path/summary.html"
